name: HTMLgenerator

on:
  push:
    branches:
      - visualisationHTML
      - main

jobs:
  createFile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.4.5

      - name: Set up Python (if you use Python for scripts)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      - name: Create HTML pages
        run: |
          python3 XML2HTML.py
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update files"
          git push
